from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List

from rules.engine import RulesError


def _load_litellm():
    try:
        from litellm import completion

        return completion
    except Exception as exc:
        raise RulesError(
            "litellm is required for --compile-rules. Install dependencies from requirements.txt."
        ) from exc


def build_adapter_contract_samples() -> List[Dict[str, str]]:
    return [
        {
            "date": "2026-03-14",
            "platform": "leetcode",
            "title": "Two Sum",
            "difficulty": "Easy",
            "link": "https://leetcode.com/problems/two-sum/",
            "contest": "",
            "language": "Python 3",
            "tags": "array, hash-table",
            "notes": "",
        },
        {
            "date": "2026-03-14",
            "platform": "codeforces",
            "title": "All-in-one Gun",
            "difficulty": "1300",
            "link": "https://codeforces.com/contest/2192/problem/C",
            "contest": "2192",
            "language": "GNU C++17",
            "tags": "dp, implementation",
            "notes": "",
        },
        {
            "date": "2026-03-14",
            "platform": "atcoder",
            "title": "B. Deconstruct Chocolate",
            "difficulty": "",
            "link": "https://atcoder.jp/contests/abc449/tasks/abc449_b",
            "contest": "abc449",
            "language": "Python (PyPy 3.11-v7.3.20)",
            "tags": "",
            "notes": "",
        },
    ]


def build_compiler_prompt(context: Dict[str, Any]) -> List[Dict[str, str]]:
    system_prompt = (
        "You are generating deterministic mapping rules for a competitive-programming tracker. "
        "Return only valid JSON matching the target schema. "
        "Prioritize exact dropdown compliance for platform values and stable column mappings."
    )
    user_prompt = (
        "Generate rules JSON using this context:\n"
        f"{json.dumps(context, indent=2)}\n\n"
        "Rules must include: version, generated_at, source_sheet_id, confidence, notes, "
        "column_map, value_maps, normalizers.\n"
        "In value_maps.platform, map canonical values (leetcode/codeforces/atcoder) "
        "to exact sheet dropdown values if possible."
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def compile_rules_with_llm(context: Dict[str, Any]) -> Dict[str, Any]:
    completion = _load_litellm()
    model = os.getenv("LITELLM_MODEL", "").strip()
    if not model:
        raise RulesError(
            "Missing LITELLM_MODEL environment variable. Example: openai/gpt-4o-mini."
        )

    response = completion(
        model=model,
        messages=build_compiler_prompt(context),
        temperature=0.0,
        response_format={"type": "json_object"},
    )
    content = (
        response["choices"][0]["message"]["content"]
        if isinstance(response, dict)
        else response.choices[0].message.content
    )

    try:
        rules = json.loads(content)
    except json.JSONDecodeError as exc:
        raise RulesError(f"LLM returned non-JSON content: {content}") from exc

    rules.setdefault("version", "1.0.0")
    rules.setdefault(
        "generated_at", datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    )
    rules.setdefault("source_sheet_id", str(context.get("sheet_id", "")))
    rules.setdefault("confidence", 0.5)
    rules.setdefault("notes", "Generated by LLM rule compiler.")
    rules.setdefault("column_map", {})
    rules.setdefault("value_maps", {"platform": {}})
    rules.setdefault(
        "normalizers", {"platform_case": "sheet-value", "date_format": "YYYY-MM-DD"}
    )
    return rules

